r"""Tooling session: three more tables for `paper/manuscript_edited.tex`, into
`paper/tables_edited/`.

The edited paper (a later session's job) keeps the ablation ladder, the conformal guarantee
and the age-band blind spot, but the manuscript it is downsized from spreads each of those
across two floats: the ladder against the two pre-registered post-A7 rungs
(`paper/tables/ablation_table.tex` + the inline `tab:exhaustion` table), the age-band gap
against the age-rule recovery (`paper/tables/table4_agegap.tex` + prose-only rule numbers),
and the conformal comparison only as a Markdown report
(`results/session9/session9_tables_report.md`), never as a `.tex` table at all. This module
renders one consolidated table per topic, each one read straight from the frozen artifact
that already backs the corresponding number in the published manuscript -- no new quantity is
computed and no split is read.

**The four "post-hoc recombination" levers are deliberately NOT included** in the consolidated
ladder (the eight-member vote, Caruana greedy, prior correction, per-class offsets, currently
rows of the hand-typed `tab:exhaustion` in `paper/manuscript.tex`). No `results/` artifact backs
those four numbers -- they were never written to a CSV or JSON, only typed directly into the
manuscript, which is itself a pre-existing Hard-Rule-4 gap this module will not extend by
retyping them a second time. The two rungs that *do* have a backing artifact
(`results/session9/new_rung_comparisons.json`: A7-oof, A8) are included. Whoever writes
`manuscript_edited.tex` should either drop the four unbacked rows or get them written to
`results/` first.

Usage:
    python -m research.ablation.render_edited_tables [--check]
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

from ml.paths import REPO_ROOT, resolve

OUT_DIR = "paper/tables_edited"
LADDER_TABLE = f"{OUT_DIR}/ablation_table_edited.tex"
CONFORMAL_TABLE = f"{OUT_DIR}/conformal_coverage_edited.tex"
AGE_TABLE = f"{OUT_DIR}/table_agegap_edited.tex"

GENERATED_BY = "%% generated by research/ablation/render_edited_tables.py -- do not hand-edit\n"

#: Rungs shown in Block A of the consolidated ladder, in order. Matches
#: paper/tables/ablation_table.tex row for row (same source, results/ablation_table.csv).
BLOCK_A = [
    ("A1", "A1_resnet50", "ResNet-50 (weakest CNN member)"),
    ("A2", "A2_convnext_tiny", "ConvNeXt-Tiny (best single on val)"),
    ("A3", "A3_swinv2_tiny", "SwinV2-Tiny (transformer)"),
    ("A4", "A4_gated_fusion", "Gated metadata fusion"),
    ("A5", "A5_soft_vote_6cnn", "Uniform soft-vote, $K=6$ CNNs"),
    ("A6", "A6_soft_vote_6cnn_tta", r"\quad + 24-view TTA"),
    ("A7", "A7_tta_dirichlet", r"\quad + Dirichlet calibration"),
]
BLOCK_B = [
    ("B1", "B_margin_abstain05", r"\quad + margin abstention @\,5\%"),
    ("B2", "B_margin_abstain10", r"\quad + margin abstention @\,10\%"),
    ("B3", "B_margin_abstain15", r"\quad + margin abstention @\,15\%"),
    ("B4", "B_margin_abstain20", r"\quad + margin abstention @\,20\%"),
]

#: The two pre-registered rungs beyond A7, and how they label against `new_rung_comparisons.json`.
BLOCK_C = [
    ("A7-oof", "A7_oof vs A7_val", "OOF-fitted Dirichlet (companion calibration rung)"),
    ("A8", "A8 vs A7_val", "30-member fold bag (uniform, no member selection)"),
]

CONFORMAL_METHODS = ("APS", "LAC", "RAPS")
CONFORMAL_CALIBRATORS = [
    ("marginal", "Marginal"),
    ("class_conditional", "Mondrian (class-conditional)"),
    ("bipartite", "Bipartite"),
]
CONFORMAL_ALPHAS = ("0.05", "0.1")

AGE_BANDS = ["<40", "40-59", "60+"]


def _f(x, nd=4) -> str:
    return f"{float(x):.{nd}f}"


def _csv(path: str) -> list[dict]:
    with open(resolve(path), encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _json(path: str):
    return json.loads(resolve(path).read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------------------
# Table: consolidated ablation ladder (Block A + Block B + the two post-A7 rungs)
# ---------------------------------------------------------------------------------------

def build_ladder_table() -> str:
    ladder = {r["rung"]: r for r in _csv("results/ablation_table.csv")}
    rungs = _json("results/session9/new_rung_comparisons.json")
    by_comparison = {c["comparison"]: c for c in rungs["comparisons"]}
    holm = rungs["holm"]
    # `holm["p_holm"]` aligns by index with `comparisons` (both built from the same iteration
    # order in run_session9_testpass.py), not by any shared key -- `members_evaluated` confirms
    # the order rather than providing one to zip against.
    assert rungs["members_evaluated"] == [c["comparison"] for c in rungs["comparisons"]]
    p_holm = dict(zip((c["comparison"] for c in rungs["comparisons"]), holm["p_holm"]))

    lines = [
        GENERATED_BY.rstrip("\n"),
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Ablation ladder on the HAM10000 held-out test split, consolidated with the "
        r"two pre-registered rungs evaluated beyond A7 (Sec.~\ref{sec:results-exhaustion} of "
        r"the full manuscript). Block A is full coverage on a common $N{=}1502$-image "
        r"denominator; Block B is selective and reports on the retained subset only, so its "
        r"rows are not directly comparable to Block A. Block C's two rungs were declared in "
        r"the pre-registered analysis plan before they existed and are Holm-corrected within "
        r"their own two-member family; both are negative in point estimate. Four "
        r"post-hoc recombination levers reported alongside these two in the full manuscript "
        r"(eight-member vote, Caruana greedy, prior correction, per-class offsets) are omitted "
        r"here -- no \texttt{results/} artifact backs them (see module docstring).}",
        r"\label{tab:ablation_edited}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4.5pt}",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"& Configuration & Coverage & $N$ & Macro-F1 (95\% CI) & Bal. acc. & Esc. sens. / missed \\",
        r"\midrule",
        r"\multicolumn{7}{l}{\textit{Block A --- full coverage, common denominator}} \\",
    ]
    for tag, rung, label in BLOCK_A:
        r = ladder[rung]
        lines.append(
            f"{tag} & {label} & {_f(r['coverage'], 3)} & {int(float(r['n']))} & "
            f"{_f(r['macro_f1'])} [{_f(r['macro_f1_ci_low'])}, {_f(r['macro_f1_ci_high'])}] & "
            f"{_f(r['balanced_accuracy'])} & "
            f"{_f(r['escalation_sensitivity'])} / {int(float(r['missed_serious']))} \\\\"
        )
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{7}{l}{\textit{Block B --- selective, denominator changes with coverage}} \\")
    for tag, rung, label in BLOCK_B:
        r = ladder[rung]
        lines.append(
            f"{tag} & {label} & {_f(r['coverage'], 3)} & {int(float(r['n']))} & "
            f"{_f(r['macro_f1'])} [{_f(r['macro_f1_ci_low'])}, {_f(r['macro_f1_ci_high'])}] & "
            f"{_f(r['balanced_accuracy'])} & "
            f"{_f(r['escalation_sensitivity'])} / {int(float(r['missed_serious']))} \\\\"
        )
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{7}{l}{\textit{Block C --- pre-registered rungs beyond A7, single test pass}} \\")
    for tag, comparison_key, label in BLOCK_C:
        c = by_comparison[comparison_key]
        ph = p_holm[comparison_key]
        lines.append(
            f"{tag} & {label} & --- & --- & "
            f"$\\Delta {c['point_estimate']:+.4f}$ "
            f"[{c['ci_low']:+.4f}, {c['ci_high']:+.4f}] & "
            f"\\multicolumn{{2}}{{c}}{{vs A7, Holm $p={ph:.3f}$ (not significant)}} \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------------------
# Table: conformal coverage (marginal vs Mondrian class-conditional vs bipartite)
# ---------------------------------------------------------------------------------------

def build_conformal_table() -> str:
    rows = {(r["method"], r["calibrator"], r["alpha"]): r
            for r in _csv("results/session9/conformal_test.csv")}

    lines = [
        GENERATED_BY.rstrip("\n"),
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Conformal coverage on the HAM10000 held-out test split ($N=1502$), marginal "
        r"vs. Mondrian class-conditional vs. bipartite calibration, at $\alpha=0.05$ and "
        r"$\alpha=0.10$. Serious coverage is coverage restricted to the escalating classes; "
        r"FRR is the false-referral rate (a serious lesion's conformal set omitting every "
        r"escalating class). Source: \texttt{results/session9/conformal\_test.csv}, the single "
        r"pre-registered test pass. Coverage here is audited empirically, not guaranteed: the "
        r"OOF calibration scores come from five fold models and the test scores from the full-"
        r"train ensemble, so no exact finite-sample guarantee transfers.}",
        r"\label{tab:conformal_edited}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{6pt}",
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Method & Calibrator & Marginal cov. & Serious cov. & FRR [95\% CI] \\",
        r"\midrule",
    ]
    for alpha in CONFORMAL_ALPHAS:
        lines.append(r"\multicolumn{5}{l}{\textit{$\alpha = %s$}} \\" % _f(alpha, 2))
        for method in CONFORMAL_METHODS:
            for calibrator, calib_label in CONFORMAL_CALIBRATORS:
                r = rows[(method, calibrator, alpha)]
                lines.append(
                    f"{method} & {calib_label} & {_f(r['marginal_coverage'], 4)} & "
                    f"{_f(r['escalating_coverage'], 4)} & "
                    f"{_f(r['frr'], 4)} [{_f(r['frr_ci_lo'], 4)}, {_f(r['frr_ci_hi'], 4)}] \\\\"
                )
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [
        r"\end{tabular}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------------------
# Table: age-band escalation sensitivity, merged with the age-rule recovery columns
# ---------------------------------------------------------------------------------------

def build_age_table() -> str:
    intervals = _csv("research/stats/results_oof/age_gap_intervals.csv")
    by_split_band = {(r["split"], r["band"]): r for r in intervals}
    oof_rule = {r["group"]: r for r in _csv("research/agerule/results_oof/lambda_by_band.csv")}
    test_rule = {(r["band"], r["rule"]): r for r in _csv("results/session9/agerule_test.csv")}

    def cp_or_boot(r) -> str:
        return "CP" if r["interval_method"] == "clopper_pearson" else "boot"

    lines = [
        GENERATED_BY.rstrip("\n"),
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Escalation sensitivity by patient age band under argmax, merged with the "
        r"age-conditional $\lambda$-rule's recovery. Validation and OOF columns are argmax "
        r"only (the rule is fitted on OOF and reported from there); the test columns compare "
        r"argmax against the frozen rule from the single pre-registered Session~9 test pass. "
        r"Intervals marked CP are exact Clopper--Pearson; those marked boot are lesion-grouped "
        r"percentile bootstrap. Sources: "
        r"\texttt{research/stats/results\_oof/age\_gap\_intervals.csv} (val, OOF argmax), "
        r"\texttt{research/agerule/results\_oof/lambda\_by\_band.csv} (OOF rule, cross-fitted, "
        r"point estimate only), \texttt{results/session9/agerule\_test.csv} (test argmax and "
        r"rule).}",
        r"\label{tab:agegap_edited}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{5pt}",
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        r" & \multicolumn{3}{c}{Internal / Out-of-fold} & \multicolumn{2}{c}{Held-out test} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}",
        r"Age band & Val argmax & OOF argmax & OOF rule ($\lambda$) & Test argmax & Test rule ($\lambda$) \\",
        r"\midrule",
    ]
    for band in AGE_BANDS:
        v = by_split_band[("val", band)]
        o = by_split_band[("oof", band)]
        orule = oof_rule[band]
        t_arg = test_rule[(band, "argmax")]
        t_rule = test_rule[(band, "lambda_rule")]
        val_cell = (f"${_f(v['sensitivity'], 3)}$ [{_f(v['ci_lo'], 3)}, {_f(v['ci_hi'], 3)}]"
                    f"$^{{\\text{{{cp_or_boot(v)}}}}}$")
        oof_cell = (f"${_f(o['sensitivity'], 3)}$ [{_f(o['ci_lo'], 3)}, {_f(o['ci_hi'], 3)}]"
                    f"$^{{\\text{{{cp_or_boot(o)}}}}}$")
        oof_rule_cell = f"${_f(orule['fit_sensitivity'], 3)}$ ($\\lambda={_f(orule['lam'], 2)}$)"
        t_arg_cell = (f"${_f(t_arg['escalation_sensitivity'], 3)}$ "
                      f"[{_f(t_arg['sens_ci_lo'], 3)}, {_f(t_arg['sens_ci_hi'], 3)}]")
        t_rule_cell = (f"${_f(t_rule['escalation_sensitivity'], 3)}$ "
                       f"[{_f(t_rule['sens_ci_lo'], 3)}, {_f(t_rule['sens_ci_hi'], 3)}]")
        label = band.replace("<", "$<$").replace("-", "--")
        lines.append(f"{label} & {val_cell} & {oof_cell} & {oof_rule_cell} & "
                     f"{t_arg_cell} & {t_rule_cell} \\\\")

    all_v = by_split_band[("val", "ALL")]
    all_o = by_split_band.get(("oof", "ALL"))
    t_arg_all = test_rule[("ALL", "argmax")]
    t_rule_all = test_rule[("ALL", "lambda_rule")]
    val_all_cell = (f"${_f(all_v['sensitivity'], 3)}$ [{_f(all_v['ci_lo'], 3)}, {_f(all_v['ci_hi'], 3)}]"
                    f"$^{{\\text{{{cp_or_boot(all_v)}}}}}$")
    if all_o is not None:
        oof_all_cell = (f"${_f(all_o['sensitivity'], 3)}$ [{_f(all_o['ci_lo'], 3)}, {_f(all_o['ci_hi'], 3)}]"
                        f"$^{{\\text{{{cp_or_boot(all_o)}}}}}$")
    else:
        oof_all_cell = "---"
    t_arg_all_cell = (f"${_f(t_arg_all['escalation_sensitivity'], 3)}$ "
                      f"[{_f(t_arg_all['sens_ci_lo'], 3)}, {_f(t_arg_all['sens_ci_hi'], 3)}]")
    t_rule_all_cell = (f"${_f(t_rule_all['escalation_sensitivity'], 3)}$ "
                       f"[{_f(t_rule_all['sens_ci_lo'], 3)}, {_f(t_rule_all['sens_ci_hi'], 3)}]")
    lines.append(r"\midrule")
    lines.append(f"All ages & {val_all_cell} & {oof_all_cell} & --- & "
                 f"{t_arg_all_cell} & {t_rule_all_cell} \\\\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="render in memory and report drift without writing the files")
    args = parser.parse_args(argv)

    outputs = {
        LADDER_TABLE: build_ladder_table(),
        CONFORMAL_TABLE: build_conformal_table(),
        AGE_TABLE: build_age_table(),
    }

    for path, tex in outputs.items():
        target = resolve(path)
        if args.check:
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            status = "up to date" if current == tex else "DRIFTED"
            print(f"{status}: {path}")
            if current != tex:
                return 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(tex, encoding="utf-8")
        rows = sum(1 for line in tex.splitlines() if line.strip().endswith(r"\\"))
        print(f"Wrote {target.relative_to(REPO_ROOT)} ({rows} rows, {len(tex):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
